Module Module2
    Sub CetakOrder(ByVal Id As Integer)
        Dim transaksi = EksekusiSQL("SELECT a.id, a.kode_invoice, a.id_member, c.nama as nama_pelanggan, a.tanggal, a.deadline, a.tanggal_bayar,a.biaya_tambahan, a.diskon,a.status, a.dibayar, a.id_user, b.nama as kasir FROM transaksi a LEFT JOIN user b ON a.id_user=b.id LEFT JOIN member c ON a.id_member=c.id WHERE a.id=" & Id & "").Select()(0)
        Dim transaksidetil = EksekusiSQL("SELECT a.id, a.id_transaksi, a.id_paket, b.nama_paket, qty, a.harga, a.diskon, a.keterangan,(a.qty*a.harga)-a.diskon as total_harga FROM transaksi_detail a LEFT JOIN paket b ON a.id_paket=b.id WHERE a.id_transaksi=" & Id & "").Select()

        Dim SourceHtml As String = ""
        SourceHtml &= vbCrLf & " <html>"

        SourceHtml &= vbCrLf & " <head>"
        SourceHtml &= vbCrLf & " <meta http-equiv=Content-Type content=""text/html; charset=windows-1252"">"
        SourceHtml &= vbCrLf & " <meta name=Generator content=""Microsoft Word 12 (filtered)"">"
        SourceHtml &= vbCrLf & " <style>"
        SourceHtml &= vbCrLf & " <!--"
        SourceHtml &= vbCrLf & "  /* Font Definitions */"
        SourceHtml &= vbCrLf & "  @font-face"
        SourceHtml &= vbCrLf & " 	{font-family:""Cambria Math"";"
        SourceHtml &= vbCrLf & " 	panose-1:2 4 5 3 5 4 6 3 2 4;}"
        SourceHtml &= vbCrLf & " @font-face"
        SourceHtml &= vbCrLf & " 	{font-family:Calibri;"
        SourceHtml &= vbCrLf & " 	panose-1:2 15 5 2 2 2 4 3 2 4;}"
        SourceHtml &= vbCrLf & "  /* Style Definitions */"
        SourceHtml &= vbCrLf & "         p.MsoNormal, li.MsoNormal, div.MsoNormal"
        SourceHtml &= vbCrLf & " 	{margin-top:0cm;"
        SourceHtml &= vbCrLf & " 	margin-right:0cm;"
        SourceHtml &= vbCrLf & " 	margin-bottom:10.0pt;"
        SourceHtml &= vbCrLf & " 	margin-left:0cm;"
        SourceHtml &= vbCrLf & " 	line-height:115%;"
        SourceHtml &= vbCrLf & " 	font-size:11.0pt;"
        SourceHtml &= vbCrLf & " 	font-family:""Calibri"",""sans-serif"";}"
        SourceHtml &= vbCrLf & "         .MsoPapDefault()"
        SourceHtml &= vbCrLf & " 	{margin-bottom:10.0pt;"
        SourceHtml &= vbCrLf & " 	line-height:115%;}"
        SourceHtml &= vbCrLf & " @page Section1"
        SourceHtml &= vbCrLf & " 	{size:155.95pt 258.0pt;"
        SourceHtml &= vbCrLf & " 	margin:8.5pt 9.9pt 14.45pt 9.65pt;}"
        SourceHtml &= vbCrLf & "         div.Section1()"
        SourceHtml &= vbCrLf & " 	{page:Section1;}"
        SourceHtml &= vbCrLf & " -->"

        SourceHtml &= vbCrLf & " .v_wrapper{"
        SourceHtml &= vbCrLf & " 	width: 219px"
        SourceHtml &= vbCrLf & " }"
        SourceHtml &= vbCrLf & " </style>"

        SourceHtml &= vbCrLf & " </head>"

        SourceHtml &= vbCrLf & " <body lang=IN>"

        SourceHtml &= vbCrLf & " <div class=Section1>"
        SourceHtml &= vbCrLf & " <div class=""v_wrapper"">"

        SourceHtml &= vbCrLf & " <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "         text(-align) : center() '><b><span style='font-family:""Arial"",""sans-serif""'>" & UCase(My.Settings.lapCompany) & "</span></b></p>"

        SourceHtml &= vbCrLf & " <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "         text(-align) : center() '><span style='font-size:4.0pt;line-height:115%;font-family:"
        SourceHtml &= vbCrLf & " ""Arial"",""sans-serif"";color:black'>Jl. Panda 4 D5 No. 6 Telp. 0877 7931 1338 –"
        SourceHtml &= vbCrLf & " 0813 1438 9331</span></p>"

        SourceHtml &= vbCrLf & " <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "         text(-align) : center() '><b><span style='font-size:7.0pt;line-height:115%;font-family:"
        SourceHtml &= vbCrLf & " ""Arial"",""sans-serif"";color:black'>----------------------------------------------------------</span></b></p>"

        SourceHtml &= vbCrLf & " <table class=MsoTableGrid border=0 cellspacing=0 cellpadding=0"
        SourceHtml &= vbCrLf & "  style='border-collapse:collapse;border:none'>"
        SourceHtml &= vbCrLf & "  <tr>"
        SourceHtml &= vbCrLf & "   <td width=83 valign=top style='width:62.1pt;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>Struk"
        SourceHtml &= vbCrLf & "   : " & Id & "</span></p>"
        SourceHtml &= vbCrLf & "   </td>"
        SourceHtml &= vbCrLf & "   <td width=113 valign=top style='width:85.1pt;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>" & Format(transaksi.Item("tanggal"), "dd/MM/yyyy HH:mm") & "</span></p>"
        SourceHtml &= vbCrLf & "   </td>"
        SourceHtml &= vbCrLf & "  </tr>"
        SourceHtml &= vbCrLf & "  <tr>"
        SourceHtml &= vbCrLf & "   <td width=83 valign=top style='width:62.1pt;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:5.0pt;font-family:""Arial"",""sans-serif""'>Kasir: " & transaksi.Item("kasir") & "</span></p>"
        SourceHtml &= vbCrLf & "   </td>"
        SourceHtml &= vbCrLf & "   <td width=113 valign=top style='width:85.1pt;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>Pelanggan: " & transaksi.Item("nama_pelanggan") & "</span></p>"
        SourceHtml &= vbCrLf & "   </td>"
        SourceHtml &= vbCrLf & "  </tr>"
        SourceHtml &= vbCrLf & " </table>"

        SourceHtml &= vbCrLf & " <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "         justify() '><b><span style='font-size:7.0pt;line-height:115%;font-family:""Arial"",""sans-serif"";"
        SourceHtml &= vbCrLf & " color:  black() '>----------------------------------------------------------</span></b></p>"

        Dim SubTotal As Double = 0
        For Each Isi In transaksidetil
            SubTotal = SubTotal + Isi.Item("total_harga")

            SourceHtml &= vbCrLf & " <table class=MsoTableGrid border=0 cellspacing=0 cellpadding=0"
            SourceHtml &= vbCrLf & "  style='border-collapse:collapse;border:none'>"
            SourceHtml &= vbCrLf & "  <tr>"
            SourceHtml &= vbCrLf & "   <td width=116 colspan=5 valign=top style='width:87.05pt;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
            SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>" & Isi.Item("nama_paket") & "</span></p>"
            SourceHtml &= vbCrLf & "   </td>"
            SourceHtml &= vbCrLf & "   <td width=80 valign=top style='width:60.15pt;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
            SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>&nbsp;</span></p>"
            SourceHtml &= vbCrLf & "   </td>"
            SourceHtml &= vbCrLf & "  </tr>"
            SourceHtml &= vbCrLf & "  <tr>"
            SourceHtml &= vbCrLf & "   <td width=25 colspan=2 valign=top style='width:18.5pt;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
            SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>X" & Isi.Item("qty") & "</span></p>"
            SourceHtml &= vbCrLf & "   </td>"
            SourceHtml &= vbCrLf & "   <td width=42 colspan=2 valign=top style='width:31.7pt;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
            SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>@" & Format(Isi.Item("qty"), "#,##0") & "</span></p>"
            SourceHtml &= vbCrLf & "   </td>"
            SourceHtml &= vbCrLf & "   <td width=49 valign=top style='width:36.85pt;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
            SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>Dsc." & Isi.Item("diskon") & "</span></p>"
            SourceHtml &= vbCrLf & "   </td>"
            SourceHtml &= vbCrLf & "   <td width=80 valign=top style='width:60.15pt;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
            SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>" & Isi.Item("total_harga") & "</span></p>"
            SourceHtml &= vbCrLf & "   </td>"
            SourceHtml &= vbCrLf & "  </tr>"
            SourceHtml &= vbCrLf & "  <tr height=0>"
            SourceHtml &= vbCrLf & "   <td width=24 style='border:none'></td>"
            SourceHtml &= vbCrLf & "   <td width=0 style='border:none'></td>"
            SourceHtml &= vbCrLf & "   <td width=41 style='border:none'></td>"
            SourceHtml &= vbCrLf & "   <td width=1 style='border:none'></td>"
            SourceHtml &= vbCrLf & "   <td width=49 style='border:none'></td>"
            SourceHtml &= vbCrLf & "   <td width=80 style='border:none'></td>"
            SourceHtml &= vbCrLf & "  </tr>"
            SourceHtml &= vbCrLf & " </table>"

        Next

        SourceHtml &= vbCrLf & " <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "         justify() '><b><span style='font-size:6.0pt;line-height:115%;font-family:""Arial"",""sans-serif""'>--------------------------------------------------------------------</span></b></p>"

        SourceHtml &= vbCrLf & " <table class=MsoTableGrid border=0 cellspacing=0 cellpadding=0"
        SourceHtml &= vbCrLf & "  style='border-collapse:collapse;border:none'>"
        SourceHtml &= vbCrLf & "  <tr>"
        SourceHtml &= vbCrLf & "   <td width=98 valign=top style='width:73.6pt;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>Subtotal</span></p>"
        SourceHtml &= vbCrLf & "   </td>"
        SourceHtml &= vbCrLf & "   <td width=98 valign=top style='width:73.6pt;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>" & Format(SubTotal, "#,##0") & "</span></p>"
        SourceHtml &= vbCrLf & "   </td>"
        SourceHtml &= vbCrLf & "  </tr>"
        SourceHtml &= vbCrLf & "  <tr>"
        SourceHtml &= vbCrLf & "   <td width=98 valign=top style='width:73.6pt;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>Biaya Tambahan</span></p>"
        SourceHtml &= vbCrLf & "   </td>"
        SourceHtml &= vbCrLf & "   <td width=98 valign=top style='width:73.6pt;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>" & Format(transaksi.Item("biaya_tambahan"), "#,##0") & "</span></p>"
        SourceHtml &= vbCrLf & "   </td>"
        SourceHtml &= vbCrLf & "  </tr>"
        SourceHtml &= vbCrLf & "  <tr>"
        SourceHtml &= vbCrLf & "   <td width=98 valign=top style='width:73.6pt;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>Total Bayar</span></p>"
        SourceHtml &= vbCrLf & "   </td>"
        SourceHtml &= vbCrLf & "   <td width=98 valign=top style='width:73.6pt;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>" & Format(SubTotal + transaksi.Item("biaya_tambahan"), "#,##0") & "</span></p>"
        SourceHtml &= vbCrLf & "   </td>"
        SourceHtml &= vbCrLf & "  </tr>"
        SourceHtml &= vbCrLf & "  <tr>"
        SourceHtml &= vbCrLf & "   <td width=98 valign=top style='width:73.6pt;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>Status: </span></p>"
        SourceHtml &= vbCrLf & "   </td>"
        SourceHtml &= vbCrLf & "   <td width=98 valign=top style='width:73.6pt;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "   <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:"
        SourceHtml &= vbCrLf & "   justify;line-height:normal'><span style='font-size:6.0pt;font-family:""Arial"",""sans-serif""'>" & IIf(transaksi.Item("dibayar") = "Dibayar", "Lunas", "order") & "</span></p>"
        SourceHtml &= vbCrLf & "   </td>"
        SourceHtml &= vbCrLf & "  </tr>"
        SourceHtml &= vbCrLf & " </table>"

        SourceHtml &= vbCrLf & " <p class=MsoNormal align=center style='text-align:center'><b><span"
        SourceHtml &= vbCrLf & " style='font-size:6.0pt;line-height:115%;font-family:""Arial"",""sans-serif""'>--------------------------------------------------------------------</span></b></p>"

        SourceHtml &= vbCrLf & " <p class=MsoNormal align=center style='text-align:center'><span"
        SourceHtml &= vbCrLf & " style='font-size:6.0pt;line-height:115%;font-family:""Arial"",""sans-serif""'>Terima"
        SourceHtml &= vbCrLf & " kasih telah menggunakan layanan kami</span></p>"

        SourceHtml &= vbCrLf & " <p class=MsoNormal align=center style='text-align:center'><b><span"
        SourceHtml &= vbCrLf & " style='font-size:6.0pt;line-height:115%;font-family:""Arial"",""sans-serif""'>--------------------------------------------------------------------</span></b></p>"

        SourceHtml &= vbCrLf & " </div>"
        SourceHtml &= vbCrLf & " </div>"

        SourceHtml &= vbCrLf & " </body>"

        SourceHtml &= vbCrLf & " </html>"


        frmsetupcetak.NamaLaporan = "Nota Order"
        frmsetupcetak.SourceHtml = SourceHtml
        frmsetupcetak.ShowDialog()

    End Sub

    Sub CetakLaporanFajarLaundry(ByVal Tampung As DataTable, ByVal TglAwal As Date, ByVal TglAkhir As Date, ByVal TotalOmset As Double, ByVal HakAkses As String)
        Dim SourceHtml As String = ""
        SourceHtml &= vbCrLf & "<html>"

        SourceHtml &= vbCrLf & "<head>"
        SourceHtml &= vbCrLf & "<meta http-equiv=Content-Type content=""text/html; charset=windows-1252"">"
        SourceHtml &= vbCrLf & "<meta name=ProgId content=Word.Document>"
        SourceHtml &= vbCrLf & "<meta name=Generator content=""Microsoft Word 12"">"
        SourceHtml &= vbCrLf & "<meta name=Originator content=""Microsoft Word 12"">"
        SourceHtml &= vbCrLf & "<link rel=File-List href=""LAPORAN%20FAJAR%20LAUNDRY_files/filelist.xml"">"
        SourceHtml &= vbCrLf & "<link rel=themeData href=""LAPORAN%20FAJAR%20LAUNDRY_files/themedata.thmx"">"
        SourceHtml &= vbCrLf & "<link rel=colorSchemeMapping"
        SourceHtml &= vbCrLf & "href=""LAPORAN%20FAJAR%20LAUNDRY_files/colorschememapping.xml"">"
        SourceHtml &= vbCrLf & "<!--[if gte mso 9]><xml>"
        SourceHtml &= vbCrLf & " <w:WordDocument>"
        SourceHtml &= vbCrLf & "  <w:View>Print</w:View>"
        SourceHtml &= vbCrLf & "  <w:SpellingState>Clean</w:SpellingState>"
        SourceHtml &= vbCrLf & "  <w:GrammarState>Clean</w:GrammarState>"
        SourceHtml &= vbCrLf & "  <w:TrackMoves>false</w:TrackMoves>"
        SourceHtml &= vbCrLf & "  <w:TrackFormatting/>"
        SourceHtml &= vbCrLf & "  <w:ValidateAgainstSchemas/>"
        SourceHtml &= vbCrLf & "  <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>"
        SourceHtml &= vbCrLf & "  <w:IgnoreMixedContent>false</w:IgnoreMixedContent>"
        SourceHtml &= vbCrLf & "  <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>"
        SourceHtml &= vbCrLf & "  <w:DoNotPromoteQF/>"
        SourceHtml &= vbCrLf & "  <w:LidThemeOther>IN</w:LidThemeOther>"
        SourceHtml &= vbCrLf & "  <w:LidThemeAsian>X-NONE</w:LidThemeAsian>"
        SourceHtml &= vbCrLf & "  <w:LidThemeComplexScript>AR-SA</w:LidThemeComplexScript>"
        SourceHtml &= vbCrLf & "  <w:Compatibility>"
        SourceHtml &= vbCrLf & "   <w:BreakWrappedTables/>"
        SourceHtml &= vbCrLf & "   <w:SnapToGridInCell/>"
        SourceHtml &= vbCrLf & "   <w:WrapTextWithPunct/>"
        SourceHtml &= vbCrLf & "   <w:UseAsianBreakRules/>"
        SourceHtml &= vbCrLf & "   <w:DontGrowAutofit/>"
        SourceHtml &= vbCrLf & "   <w:SplitPgBreakAndParaMark/>"
        SourceHtml &= vbCrLf & "   <w:DontVertAlignCellWithSp/>"
        SourceHtml &= vbCrLf & "   <w:DontBreakConstrainedForcedTables/>"
        SourceHtml &= vbCrLf & "   <w:DontVertAlignInTxbx/>"
        SourceHtml &= vbCrLf & "   <w:Word11KerningPairs/>"
        SourceHtml &= vbCrLf & "   <w:CachedColBalance/>"
        SourceHtml &= vbCrLf & "  </w:Compatibility>"
        SourceHtml &= vbCrLf & "  <w:BrowserLevel>MicrosoftInternetExplorer4</w:BrowserLevel>"
        SourceHtml &= vbCrLf & "  <m:mathPr>"
        SourceHtml &= vbCrLf & "   <m:mathFont m:val=""Cambria Math""/>"
        SourceHtml &= vbCrLf & "   <m:brkBin m:val=""before""/>"
        SourceHtml &= vbCrLf & "   <m:brkBinSub m:val=""--""/>"
        SourceHtml &= vbCrLf & "   <m:smallFrac m:val=""off""/>"
        SourceHtml &= vbCrLf & "   <m:dispDef/>"
        SourceHtml &= vbCrLf & "   <m:lMargin m:val=""0""/>"
        SourceHtml &= vbCrLf & "   <m:rMargin m:val=""0""/>"
        SourceHtml &= vbCrLf & "   <m:defJc m:val=""centerGroup""/>"
        SourceHtml &= vbCrLf & "   <m:wrapIndent m:val=""1440""/>"
        SourceHtml &= vbCrLf & "   <m:intLim m:val=""subSup""/>"
        SourceHtml &= vbCrLf & "   <m:naryLim m:val=""undOvr""/>"
        SourceHtml &= vbCrLf & "  </m:mathPr></w:WordDocument>"
        SourceHtml &= vbCrLf & "</xml><![endif]--><!--[if gte mso 9]><xml>"
        SourceHtml &= vbCrLf & " <w:LatentStyles DefLockedState=""false"" DefUnhideWhenUsed=""true"""
        SourceHtml &= vbCrLf & "  DefSemiHidden=""true"" DefQFormat=""false"" DefPriority=""99"""
        SourceHtml &= vbCrLf & "  LatentStyleCount=""267"">"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""0"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""Normal""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""9"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""heading 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""9"" QFormat=""true"" Name=""heading 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""9"" QFormat=""true"" Name=""heading 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""9"" QFormat=""true"" Name=""heading 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""9"" QFormat=""true"" Name=""heading 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""9"" QFormat=""true"" Name=""heading 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""9"" QFormat=""true"" Name=""heading 7""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""9"" QFormat=""true"" Name=""heading 8""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""9"" QFormat=""true"" Name=""heading 9""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""39"" Name=""toc 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""39"" Name=""toc 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""39"" Name=""toc 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""39"" Name=""toc 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""39"" Name=""toc 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""39"" Name=""toc 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""39"" Name=""toc 7""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""39"" Name=""toc 8""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""39"" Name=""toc 9""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""35"" QFormat=""true"" Name=""caption""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""10"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""Title""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""1"" Name=""Default Paragraph Font""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""11"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""Subtitle""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""22"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""Strong""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""20"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""Emphasis""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""59"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Table Grid""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" UnhideWhenUsed=""false"" Name=""Placeholder Text""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""1"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""No Spacing""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""60"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Shading""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""61"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light List""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""62"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Grid""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""63"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""64"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""65"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""66"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""67"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""68"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""69"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""70"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Dark List""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""71"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Shading""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""72"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful List""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""73"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Grid""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""60"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Shading Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""61"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light List Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""62"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Grid Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""63"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 1 Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""64"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 2 Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""65"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 1 Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" UnhideWhenUsed=""false"" Name=""Revision""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""34"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""List Paragraph""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""29"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""Quote""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""30"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""Intense Quote""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""66"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 2 Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""67"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 1 Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""68"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 2 Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""69"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 3 Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""70"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Dark List Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""71"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Shading Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""72"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful List Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""73"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Grid Accent 1""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""60"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Shading Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""61"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light List Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""62"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Grid Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""63"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 1 Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""64"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 2 Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""65"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 1 Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""66"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 2 Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""67"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 1 Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""68"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 2 Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""69"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 3 Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""70"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Dark List Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""71"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Shading Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""72"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful List Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""73"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Grid Accent 2""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""60"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Shading Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""61"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light List Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""62"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Grid Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""63"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 1 Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""64"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 2 Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""65"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 1 Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""66"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 2 Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""67"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 1 Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""68"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 2 Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""69"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 3 Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""70"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Dark List Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""71"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Shading Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""72"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful List Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""73"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Grid Accent 3""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""60"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Shading Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""61"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light List Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""62"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Grid Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""63"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 1 Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""64"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 2 Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""65"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 1 Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""66"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 2 Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""67"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 1 Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""68"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 2 Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""69"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 3 Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""70"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Dark List Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""71"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Shading Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""72"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful List Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""73"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Grid Accent 4""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""60"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Shading Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""61"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light List Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""62"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Grid Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""63"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 1 Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""64"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 2 Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""65"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 1 Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""66"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 2 Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""67"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 1 Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""68"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 2 Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""69"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 3 Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""70"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Dark List Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""71"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Shading Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""72"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful List Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""73"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Grid Accent 5""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""60"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Shading Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""61"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light List Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""62"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Light Grid Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""63"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 1 Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""64"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Shading 2 Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""65"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 1 Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""66"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium List 2 Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""67"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 1 Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""68"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 2 Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""69"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Medium Grid 3 Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""70"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Dark List Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""71"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Shading Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""72"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful List Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""73"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" Name=""Colorful Grid Accent 6""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""19"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""Subtle Emphasis""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""21"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""Intense Emphasis""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""31"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""Subtle Reference""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""32"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""Intense Reference""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""33"" SemiHidden=""false"""
        SourceHtml &= vbCrLf & "   UnhideWhenUsed=""false"" QFormat=""true"" Name=""Book Title""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""37"" Name=""Bibliography""/>"
        SourceHtml &= vbCrLf & "  <w:LsdException Locked=""false"" Priority=""39"" QFormat=""true"" Name=""TOC Heading""/>"
        SourceHtml &= vbCrLf & " </w:LatentStyles>"
        SourceHtml &= vbCrLf & "</xml><![endif]-->"
        SourceHtml &= vbCrLf & "<style>"
        SourceHtml &= vbCrLf & "<!--"
        SourceHtml &= vbCrLf & " /* Font Definitions */"
        SourceHtml &= vbCrLf & " @font-face"
        SourceHtml &= vbCrLf & "	{font-family:""Cambria Math"";"
        SourceHtml &= vbCrLf & "	panose-1:2 4 5 3 5 4 6 3 2 4;"
        SourceHtml &= vbCrLf & "	mso-font-charset:1;"
        SourceHtml &= vbCrLf & "	mso-generic-font-family:roman;"
        SourceHtml &= vbCrLf & "	mso-font-format:other;"
        SourceHtml &= vbCrLf & "	mso-font-pitch:variable;"
        SourceHtml &= vbCrLf & "	mso-font-signature:0 0 0 0 0 0;}"
        SourceHtml &= vbCrLf & "@font-face"
        SourceHtml &= vbCrLf & "	{font-family:Calibri;"
        SourceHtml &= vbCrLf & "	panose-1:2 15 5 2 2 2 4 3 2 4;"
        SourceHtml &= vbCrLf & "	mso-font-charset:0;"
        SourceHtml &= vbCrLf & "	mso-generic-font-family:swiss;"
        SourceHtml &= vbCrLf & "	mso-font-pitch:variable;"
        SourceHtml &= vbCrLf & "	mso-font-signature:-536859905 -1073732485 9 0 511 0;}"
        SourceHtml &= vbCrLf & " /* Style Definitions */"
        SourceHtml &= vbCrLf & "        p.MsoNormal, li.MsoNormal, div.MsoNormal"
        SourceHtml &= vbCrLf & "	{mso-style-unhide:no;"
        SourceHtml &= vbCrLf & "	mso-style-qformat:yes;"
        SourceHtml &= vbCrLf & "	mso-style-parent:"""";"
        SourceHtml &= vbCrLf & "	margin-top:0cm;"
        SourceHtml &= vbCrLf & "	margin-right:0cm;"
        SourceHtml &= vbCrLf & "	margin-bottom:10.0pt;"
        SourceHtml &= vbCrLf & "	margin-left:0cm;"
        SourceHtml &= vbCrLf & "	line-height:115%;"
        SourceHtml &= vbCrLf & "	mso-pagination:widow-orphan;"
        SourceHtml &= vbCrLf & "	font-size:11.0pt;"
        SourceHtml &= vbCrLf & "	font-family:""Calibri"",""sans-serif"";"
        SourceHtml &= vbCrLf & "	mso-fareast-font-family:""Times New Roman"";"
        SourceHtml &= vbCrLf & "	mso-fareast-theme-font:minor-fareast;}"
        SourceHtml &= vbCrLf & "        p.MsoListParagraph, li.MsoListParagraph, div.MsoListParagraph"
        SourceHtml &= vbCrLf & "	{mso-style-priority:34;"
        SourceHtml &= vbCrLf & "	mso-style-unhide:no;"
        SourceHtml &= vbCrLf & "	mso-style-qformat:yes;"
        SourceHtml &= vbCrLf & "	margin-top:0cm;"
        SourceHtml &= vbCrLf & "	margin-right:0cm;"
        SourceHtml &= vbCrLf & "	margin-bottom:10.0pt;"
        SourceHtml &= vbCrLf & "	margin-left:36.0pt;"
        SourceHtml &= vbCrLf & "	line-height:115%;"
        SourceHtml &= vbCrLf & "	mso-pagination:widow-orphan;"
        SourceHtml &= vbCrLf & "	font-size:11.0pt;"
        SourceHtml &= vbCrLf & "	font-family:""Calibri"",""sans-serif"";"
        SourceHtml &= vbCrLf & "	mso-fareast-font-family:""Times New Roman"";"
        SourceHtml &= vbCrLf & "	mso-fareast-theme-font:minor-fareast;}"
        SourceHtml &= vbCrLf & "        p.msolistparagraphcxspfirst, li.msolistparagraphcxspfirst, div.msolistparagraphcxspfirst"
        SourceHtml &= vbCrLf & "	{mso-style-name:msolistparagraphcxspfirst;"
        SourceHtml &= vbCrLf & "	mso-style-unhide:no;"
        SourceHtml &= vbCrLf & "	margin-top:0cm;"
        SourceHtml &= vbCrLf & "	margin-right:0cm;"
        SourceHtml &= vbCrLf & "	margin-bottom:0cm;"
        SourceHtml &= vbCrLf & "	margin-left:36.0pt;"
        SourceHtml &= vbCrLf & "	margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "	line-height:115%;"
        SourceHtml &= vbCrLf & "	mso-pagination:widow-orphan;"
        SourceHtml &= vbCrLf & "	font-size:11.0pt;"
        SourceHtml &= vbCrLf & "	font-family:""Calibri"",""sans-serif"";"
        SourceHtml &= vbCrLf & "	mso-fareast-font-family:""Times New Roman"";"
        SourceHtml &= vbCrLf & "	mso-fareast-theme-font:minor-fareast;}"
        SourceHtml &= vbCrLf & "        p.msolistparagraphcxspmiddle, li.msolistparagraphcxspmiddle, div.msolistparagraphcxspmiddle"
        SourceHtml &= vbCrLf & "	{mso-style-name:msolistparagraphcxspmiddle;"
        SourceHtml &= vbCrLf & "	mso-style-unhide:no;"
        SourceHtml &= vbCrLf & "	margin-top:0cm;"
        SourceHtml &= vbCrLf & "	margin-right:0cm;"
        SourceHtml &= vbCrLf & "	margin-bottom:0cm;"
        SourceHtml &= vbCrLf & "	margin-left:36.0pt;"
        SourceHtml &= vbCrLf & "	margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "	line-height:115%;"
        SourceHtml &= vbCrLf & "	mso-pagination:widow-orphan;"
        SourceHtml &= vbCrLf & "	font-size:11.0pt;"
        SourceHtml &= vbCrLf & "	font-family:""Calibri"",""sans-serif"";"
        SourceHtml &= vbCrLf & "	mso-fareast-font-family:""Times New Roman"";"
        SourceHtml &= vbCrLf & "	mso-fareast-theme-font:minor-fareast;}"
        SourceHtml &= vbCrLf & "        p.msolistparagraphcxsplast, li.msolistparagraphcxsplast, div.msolistparagraphcxsplast"
        SourceHtml &= vbCrLf & "	{mso-style-name:msolistparagraphcxsplast;"
        SourceHtml &= vbCrLf & "	mso-style-unhide:no;"
        SourceHtml &= vbCrLf & "	margin-top:0cm;"
        SourceHtml &= vbCrLf & "	margin-right:0cm;"
        SourceHtml &= vbCrLf & "	margin-bottom:10.0pt;"
        SourceHtml &= vbCrLf & "	margin-left:36.0pt;"
        SourceHtml &= vbCrLf & "	line-height:115%;"
        SourceHtml &= vbCrLf & "	mso-pagination:widow-orphan;"
        SourceHtml &= vbCrLf & "	font-size:11.0pt;"
        SourceHtml &= vbCrLf & "	font-family:""Calibri"",""sans-serif"";"
        SourceHtml &= vbCrLf & "	mso-fareast-font-family:""Times New Roman"";"
        SourceHtml &= vbCrLf & "	mso-fareast-theme-font:minor-fareast;}"
        SourceHtml &= vbCrLf & "        p.msopapdefault, li.msopapdefault, div.msopapdefault"
        SourceHtml &= vbCrLf & "	{mso-style-name:msopapdefault;"
        SourceHtml &= vbCrLf & "	mso-style-unhide:no;"
        SourceHtml &= vbCrLf & "	mso-margin-top-alt:auto;"
        SourceHtml &= vbCrLf & "	margin-right:0cm;"
        SourceHtml &= vbCrLf & "	margin-bottom:10.0pt;"
        SourceHtml &= vbCrLf & "	margin-left:0cm;"
        SourceHtml &= vbCrLf & "	line-height:115%;"
        SourceHtml &= vbCrLf & "	mso-pagination:widow-orphan;"
        SourceHtml &= vbCrLf & "	font-size:12.0pt;"
        SourceHtml &= vbCrLf & "	font-family:""Times New Roman"",""serif"";"
        SourceHtml &= vbCrLf & "	mso-fareast-font-family:""Times New Roman"";"
        SourceHtml &= vbCrLf & "	mso-fareast-theme-font:minor-fareast;}"
        SourceHtml &= vbCrLf & "        p.vwrapper, li.vwrapper, div.vwrapper"
        SourceHtml &= vbCrLf & "	{mso-style-name:v_wrapper;"
        SourceHtml &= vbCrLf & "	mso-style-unhide:no;"
        SourceHtml &= vbCrLf & "	mso-margin-top-alt:auto;"
        SourceHtml &= vbCrLf & "	margin-right:0cm;"
        SourceHtml &= vbCrLf & "	mso-margin-bottom-alt:auto;"
        SourceHtml &= vbCrLf & "	margin-left:0cm;"
        SourceHtml &= vbCrLf & "	mso-pagination:widow-orphan;"
        SourceHtml &= vbCrLf & "	font-size:12.0pt;"
        SourceHtml &= vbCrLf & "	font-family:""Times New Roman"",""serif"";"
        SourceHtml &= vbCrLf & "	mso-fareast-font-family:""Times New Roman"";"
        SourceHtml &= vbCrLf & "	mso-fareast-theme-font:minor-fareast;}"
        SourceHtml &= vbCrLf & "        .MsoChpDefault()"
        SourceHtml &= vbCrLf & "	{mso-style-type:export-only;"
        SourceHtml &= vbCrLf & "	mso-default-props:yes;"
        SourceHtml &= vbCrLf & "	font-size:10.0pt;"
        SourceHtml &= vbCrLf & "	mso-ansi-font-size:10.0pt;"
        SourceHtml &= vbCrLf & "	mso-bidi-font-size:10.0pt;}"
        SourceHtml &= vbCrLf & "        .MsoPapDefault()"
        SourceHtml &= vbCrLf & "	{mso-style-type:export-only;"
        SourceHtml &= vbCrLf & "	margin-bottom:10.0pt;"
        SourceHtml &= vbCrLf & "	line-height:115%;}"
        SourceHtml &= vbCrLf & "@page Section1"
        SourceHtml &= vbCrLf & "	{size:841.9pt 595.3pt;"
        SourceHtml &= vbCrLf & "	margin:72.0pt 0cm 72.0pt 0cm;"
        SourceHtml &= vbCrLf & "	mso-header-margin:35.4pt;"
        SourceHtml &= vbCrLf & "	mso-footer-margin:35.4pt;"
        SourceHtml &= vbCrLf & "	mso-paper-source:0;}"
        SourceHtml &= vbCrLf & "        div.Section1()"
        SourceHtml &= vbCrLf & "	{page:Section1;}"
        SourceHtml &= vbCrLf & "-->"
        SourceHtml &= vbCrLf & ".v_wrapper {"
        SourceHtml &= vbCrLf & "	width: 1285px"
        SourceHtml &= vbCrLf & "}"
        SourceHtml &= vbCrLf & "</style>"
        SourceHtml &= vbCrLf & "<!--[if gte mso 10]>"
        SourceHtml &= vbCrLf & "<style>"
        SourceHtml &= vbCrLf & " /* Style Definitions */"
        SourceHtml &= vbCrLf & "        table.MsoNormalTable()"
        SourceHtml &= vbCrLf & "	{mso-style-name:""Table Normal"";"
        SourceHtml &= vbCrLf & "	mso-tstyle-rowband-size:0;"
        SourceHtml &= vbCrLf & "	mso-tstyle-colband-size:0;"
        SourceHtml &= vbCrLf & "	mso-style-noshow:yes;"
        SourceHtml &= vbCrLf & "	mso-style-priority:99;"
        SourceHtml &= vbCrLf & "	mso-style-qformat:yes;"
        SourceHtml &= vbCrLf & "	mso-style-parent:"""";"
        SourceHtml &= vbCrLf & "	mso-padding-alt:0cm 5.4pt 0cm 5.4pt;"
        SourceHtml &= vbCrLf & "	mso-para-margin-top:0cm;"
        SourceHtml &= vbCrLf & "	mso-para-margin-right:0cm;"
        SourceHtml &= vbCrLf & "	mso-para-margin-bottom:10.0pt;"
        SourceHtml &= vbCrLf & "	mso-para-margin-left:0cm;"
        SourceHtml &= vbCrLf & "	line-height:115%;"
        SourceHtml &= vbCrLf & "	mso-pagination:widow-orphan;"
        SourceHtml &= vbCrLf & "	font-size:10.0pt;"
        SourceHtml &= vbCrLf & "	font-family:""Times New Roman"",""serif"";}"
        SourceHtml &= vbCrLf & "</style>"
        SourceHtml &= vbCrLf & "<![endif]--><!--[if gte mso 9]><xml>"
        SourceHtml &= vbCrLf & " <o:shapedefaults v:ext=""edit"" spidmax=""2050""/>"
        SourceHtml &= vbCrLf & "</xml><![endif]--><!--[if gte mso 9]><xml>"
        SourceHtml &= vbCrLf & " <o:shapelayout v:ext=""edit"">"
        SourceHtml &= vbCrLf & "  <o:idmap v:ext=""edit"" data=""1""/>"
        SourceHtml &= vbCrLf & " </o:shapelayout></xml><![endif]-->"
        SourceHtml &= vbCrLf & "</head>"

        SourceHtml &= vbCrLf & "<body lang=IN style='tab-interval:36.0pt'>"

        SourceHtml &= vbCrLf & "<div class=Section1>"

        SourceHtml &= vbCrLf & "<div class=""v_wrapper"">"

        SourceHtml &= vbCrLf & "<p class=MsoNormal align=center style='margin-top:0cm;margin-right:-67.55pt;"
        SourceHtml &= vbCrLf & "margin-bottom:10.0pt;margin-left:-70.9pt;text-align:center'><b><span"
        SourceHtml &= vbCrLf & "style='font-size:18.0pt;line-height:115%;font-family:""Arial"",""sans-serif""'>LAPORAN"
        SourceHtml &= vbCrLf & "" & UCase(My.Settings.lapCompany) & "</span></b></p>"

        SourceHtml &= vbCrLf & "<p class=MsoNormal align=center style='text-align:center'><span"
        SourceHtml &= vbCrLf & "style='font-family:""Arial"",""sans-serif""'>PERIODE " & Format(TglAwal.Date, ("dd-MM-yyyy")) & " S/D " & Format(TglAkhir.Date, ("dd-MM-yyyy")) & " </span></p>"

        SourceHtml &= vbCrLf & "<p class=MsoNormal style='margin-left:21.3pt'><span style='font-family:""Arial"",""sans-serif""'>Hak"
        SourceHtml &= vbCrLf & "Akses = " & HakAkses & "</span></p>"

        SourceHtml &= vbCrLf & "<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=1087"
        SourceHtml &= vbCrLf & " style='margin-left:12.5pt;border-collapse:collapse;mso-table-layout-alt:fixed;"
        SourceHtml &= vbCrLf & " mso-yfti-tbllook:1184;mso-padding-alt:0cm 0cm 0cm 0cm'>"
        SourceHtml &= vbCrLf & " <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>"
        SourceHtml &= vbCrLf & "  <td width=38 valign=top style='width:1.0cm;border:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-bottom:solid white 3.0pt;background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-indent:"
        SourceHtml &= vbCrLf & "  1.65pt;line-height:normal'><b><span style='font-size:10.0pt;font-family:""Arial"",""sans-serif"";"
        SourceHtml &= vbCrLf & "color:  white() '>No</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=85 valign=top style='width:63.8pt;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>tanggal</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=76 valign=top style='width:2.0cm;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>Id transaksi</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=66 valign=top style='width:49.6pt;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>Kode Invoice</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=85 valign=top style='width:63.8pt;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>Nama Pelanggan</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=95 valign=top style='width:70.9pt;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>Batas waktu</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=85 valign=top style='width:63.75pt;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>Tanggal Bayar</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=57 valign=top style='width:42.55pt;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>Total Harga</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=85 valign=top style='width:63.8pt;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>Biaya Tambahan</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=66 valign=top style='width:49.6pt;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>Diskon </span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=94 valign=top style='width:70.85pt;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>Total Biaya</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=57 valign=top style='width:42.55pt;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>Status</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=104 valign=top style='width:77.95pt;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>dibayar</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & "  <td width=95 valign=top style='width:70.9pt;border-top:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  border-left:none;border-bottom:solid white 3.0pt;border-right:solid white 1.0pt;"
        SourceHtml &= vbCrLf & "  background:#4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
        SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
        SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-size:10.0pt;"
        SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif"";color:white'>kasir</span></b></p>"
        SourceHtml &= vbCrLf & "  </td>"
        SourceHtml &= vbCrLf & " </tr>"

        Dim Urut As Integer = 1
        For Each Isi In Tampung.Select()

            SourceHtml &= vbCrLf & " <tr style='mso-yfti-irow:1;mso-yfti-lastrow:yes'>"
            SourceHtml &= vbCrLf & "  <td width=38 valign=top style='width:1.0cm;border-top:none;border-left:solid white 1.0pt;"
            SourceHtml &= vbCrLf & "  border-bottom:solid white 1.0pt;border-right:solid white 3.0pt;background:"
            SourceHtml &= vbCrLf & "  #4F81BD;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoListParagraph align=center style='margin-top:0cm;margin-right:"
            SourceHtml &= vbCrLf & "  0cm;margin-bottom:0cm;margin-left:14.2pt;margin-bottom:.0001pt;text-align:"
            SourceHtml &= vbCrLf & "  center;text-indent:-14.2pt;line-height:normal'><b><span style='font-size:"
            SourceHtml &= vbCrLf & "  10.0pt;font-family:""Arial"",""sans-serif"";color:white'>" & Urut & ".</span></b><b><span"
            SourceHtml &= vbCrLf & "  style='font-size:7.0pt;font-family:""Times New Roman"",""serif"";color:white'>&nbsp;&nbsp;"
            SourceHtml &= vbCrLf & "  </span></b><b><span style='font-size:10.0pt;font-family:""Arial"",""sans-serif"";"
            SourceHtml &= vbCrLf & "color:  white() '>&nbsp;</span></b></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=85 valign=top style='width:63.8pt;border-top:none;border-left:none;"
            SourceHtml &= vbCrLf & "  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;background:"
            SourceHtml &= vbCrLf & "  #A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Format(Isi.Item("tanggal"), "dd-MM-yyyy") & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=76 valign=top style='width:2.0cm;border-top:none;border-left:none;"
            SourceHtml &= vbCrLf & "  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;background:"
            SourceHtml &= vbCrLf & "  #A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Isi.Item("id") & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=66 valign=top style='width:49.6pt;border-top:none;border-left:none;"
            SourceHtml &= vbCrLf & "  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;background:"
            SourceHtml &= vbCrLf & "  #A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Isi.Item("kode_invoice") & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=85 valign=top style='width:63.8pt;border-top:none;border-left:none;"
            SourceHtml &= vbCrLf & "  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;background:"
            SourceHtml &= vbCrLf & "  #A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Isi.Item("nama_pelanggan") & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=95 valign=top style='width:70.9pt;border-top:none;border-left:none;"
            SourceHtml &= vbCrLf & "  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;background:"
            SourceHtml &= vbCrLf & "  #A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Format(Isi.Item("deadline"), ("dd-MM-yyyy")) & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=85 valign=top style='width:63.75pt;border-top:none;border-left:"
            SourceHtml &= vbCrLf & "  none;border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;"
            SourceHtml &= vbCrLf & "  background:#A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Format(Isi.Item("tanggal_bayar"), ("dd-MM-yyyy")) & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=57 valign=top style='width:42.55pt;border-top:none;border-left:"
            SourceHtml &= vbCrLf & "  none;border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;"
            SourceHtml &= vbCrLf & "  background:#A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Format(Isi.Item("total_harga"), ("#,##0")) & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=85 valign=top style='width:63.8pt;border-top:none;border-left:none;"
            SourceHtml &= vbCrLf & "  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;background:"
            SourceHtml &= vbCrLf & "  #A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Format(Isi.Item("biaya_tambahan"), ("#,##0")) & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=66 valign=top style='width:49.6pt;border-top:none;border-left:none;"
            SourceHtml &= vbCrLf & "  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;background:"
            SourceHtml &= vbCrLf & "  #A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Format(Isi.Item("diskon"), ("#,##0")) & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=94 valign=top style='width:70.85pt;border-top:none;border-left:"
            SourceHtml &= vbCrLf & "  none;border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;"
            SourceHtml &= vbCrLf & "  background:#A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Format(Isi.Item("total_biaya"), ("#,##0")) & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=57 valign=top style='width:42.55pt;border-top:none;border-left:"
            SourceHtml &= vbCrLf & "  none;border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;"
            SourceHtml &= vbCrLf & "  background:#A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Isi.Item("status") & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=104 valign=top style='width:77.95pt;border-top:none;border-left:"
            SourceHtml &= vbCrLf & "  none;border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;"
            SourceHtml &= vbCrLf & "  background:#A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Isi.Item("dibayar") & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & "  <td width=95 valign=top style='width:70.9pt;border-top:none;border-left:none;"
            SourceHtml &= vbCrLf & "  border-bottom:solid white 1.0pt;border-right:solid white 1.0pt;background:"
            SourceHtml &= vbCrLf & "  #A7BFDE;padding:0cm 5.4pt 0cm 5.4pt'>"
            SourceHtml &= vbCrLf & "  <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;"
            SourceHtml &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-size:10.0pt;"
            SourceHtml &= vbCrLf & "  font-family:""Arial"",""sans-serif""'>" & Isi.Item("kasir") & "</span></p>"
            SourceHtml &= vbCrLf & "  </td>"
            SourceHtml &= vbCrLf & " </tr>"

            Urut += 1
        Next

        SourceHtml &= vbCrLf & "</table>"

        SourceHtml &= vbCrLf & "<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt'><span"
        SourceHtml &= vbCrLf & "style='font-size:4.0pt;line-height:115%;font-family:""Arial"",""sans-serif""'>&nbsp;</span></p>"

        SourceHtml &= vbCrLf & "<p class=MsoNormal style='margin-left:21.3pt'><b><span style='font-family:""Arial"",""sans-serif""'>Total"
        SourceHtml &= vbCrLf & "Omset = Rp." & Format(TotalOmset, "#,##0") & ",-</span></b></p>"

        SourceHtml &= vbCrLf & "<p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;"
        SourceHtml &= vbCrLf & "margin-left:519.3pt;margin-bottom:.0001pt;text-indent:20.7pt'><b><span"
        SourceHtml &= vbCrLf & "style='font-size:12.0pt;line-height:115%;font-family:""Arial"",""sans-serif""'>" & My.Settings.lapAlamat & ","
        SourceHtml &= vbCrLf & "" & Format(Now, "dd MMMM yyyy") & "</span></b></p>"

        SourceHtml &= vbCrLf & "<p class=MsoNormal style='margin-left:612.0pt'><b><span style='font-size:12.0pt;"
        SourceHtml &= vbCrLf & "line-height:115%;font-family:""Arial"",""sans-serif""'>Menyetujui</span></b></p>"

        SourceHtml &= vbCrLf & "<p class=MsoNormal style='margin-left:612.0pt'><b><span style='font-size:12.0pt;"
        SourceHtml &= vbCrLf & "line-height:115%;font-family:""Arial"",""sans-serif""'>&nbsp;</span></b></p>"

        SourceHtml &= vbCrLf & "<p class=MsoNormal style='margin-left:612.0pt'><b><span style='font-size:12.0pt;"
        SourceHtml &= vbCrLf & "line-height:115%;font-family:""Arial"",""sans-serif""'>&nbsp;</span></b></p>"

        SourceHtml &= vbCrLf & "<p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;"
        SourceHtml &= vbCrLf & "margin-left:612.0pt;margin-bottom:.0001pt'><b><span style='font-size:12.0pt;"
        SourceHtml &= vbCrLf & "line-height:115%;font-family:""Arial"",""sans-serif""'>" & My.Settings.lapPimpinan & "</span></b></p>"

        SourceHtml &= vbCrLf & "<p class=MsoNormal style='margin-left:612.0pt'><span style='font-size:12.0pt;"
        SourceHtml &= vbCrLf & "line-height:115%;font-family:""Arial"",""sans-serif""'>pimpinan</span></p>"

        SourceHtml &= vbCrLf & "<p class=MsoNormal><b><span style='font-size:12.0pt;line-height:115%;"
        SourceHtml &= vbCrLf & "font-family:""Arial"",""sans-serif""'>&nbsp;</span></b></p>"

        SourceHtml &= vbCrLf & "</div>"

        SourceHtml &= vbCrLf & "</div>"

        SourceHtml &= vbCrLf & "</body>"

        SourceHtml &= vbCrLf & "</html>"
        frmsetupcetak.NamaLaporan = "Laporan Laundry"
        frmsetupcetak.SourceHtml = SourceHtml
        frmsetupcetak.ShowDialog()

    End Sub
End Module
